### PR TITLE
Refactor completion of generated document

### PR DESCRIPTION
**Pull request by jsimons1989**
Rename GeneratedDocument to DocumentGenerationCompleted as part of splitting submitted-data-document-generated into 3 separate topics (started, completed and failed).

Schema has been updated to have fields specific to the completion of the generated document:
- User ID
- GUID
- Description (temporarily hard coded for abridged accounts in generation service)
- Document size
- Document time (made up date for accounts)
- Document generation time

Changes have also been made to document-generator-core on the same feature branch name.

Resolves: FAPI-417, FAPI-418, FAPI-411

### CODE REVIEW

**Comment by davidmort** [comment]
theres a test folder within the "main" folder src/main/test/uk/gov/companieshouse/accounts/AvroSerializerTest.java, is this right?

**Comment by davidmort** [comment]
The "Getting Started" part of the readme doesn't make sense, its says but there no Makefile? also it says about using a start.sh script which doesn't exist?

**Comment by mattrout92** [comment]
These comments are all part of another story and not the ones we have committed to this sprint.

**Comment by davidmort** [comment]
fair point, but i'm expecting to see another pull request with these changes in very soon :)

**Pull request merged**
